name: Exécute les tests unitaires

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
              - 'main.js'
              - 'package.json'
      - name: Get package version and name
        id: package
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.src == 'true'
        shell: bash
        run: |
          echo 'test'
